version: "1"
rules:
  - base: auto-merge
    upstream: orzogc:master
    mergeMethod: merge
    conflictReviewers: 
      - MixAnKun
  - base: master
    upstream: orzogc:master
    mergeMethod: hardreset
    mergeUnstable: true
