name: MixAn Build Test

on:
  push:
    branches: [ auto-merge ]
  pull_request:
    branches: [ auto-merge ]
  workflow_dispatch:

jobs:
  Build-Offical-Testonly:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Build Offical Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        file: 'Dockerfile'
        build-args: |
          "IGNORE_CHINA_MIRROR=1"
          "NODE_OPTIONS=--openssl-legacy-provider"
  Build-NoWeb-Publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        
    - name: Login registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.PUSH_REGISTRY }}
        username: ${{ secrets.PUSH_USERNAME }}
        password: ${{ secrets.PUSH_PASSWORD }}
        
    - name: Build NoWeb Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        file: 'Dockerfile.noweb'
        build-args: IGNORE_CHINA_MIRROR=1
        tags: ${{ secrets.PUSH_REGISTRY }}/${{ secrets.PUSH_USERNAME }}/${{ secrets.PUSH_NAME }}:latest
